#!/usr/bin/env ruby

require "fileutils"
require "pathname"

Pathname(__FILE__).dirname.entries.select{ |f| f.extname == ".sym" }.each do |source|
  target = File.expand_path("~/.#{source.basename(".sym")}")
  puts `ln -vnfs #{source.realpath} #{target}`
end
