---
- name: "install plugins"
  command: "bash -lc 'asdf plugin-add {{ item.name }}'"
  args:
    creates: "{{ ansible_facts['env']['HOME'] }}/.asdf/plugins/{{ item.name }}"
  with_items: "{{ asdf_plugins }}"
  when: asdf_plugins|length > 0
  ignore_errors: True

- name: "install apps"
  command: "bash -lc 'asdf install {{ item.0.name }} {{ item.1 }}'"
  args:
    creates: "{{ ansible_facts['env']['HOME'] }}/.asdf/installs/{{ item.0.name }}/{{ item.1 }}"
  with_subelements:
    - "{{ asdf_plugins }}"
    - versions
    - flags:
      skip_missing: True
  when: asdf_plugins|length > 0

- name: "set global app versions"
  command: "bash -lc 'asdf global {{ item.name }} {{ item.global | default(item.versions[0]) }}'"
  when: item.versions is defined
  with_items: "{{ asdf_plugins }}"

- name: "set asdfrc"
  template:
    src: "asdfrc.j2"
    dest: "{{ ansible_facts['env']['HOME'] }}/.asdfrc"
    mode: 0644
