---
- file:
    src: '~/projects/dotfiles/{{ item }}.sym'
    dest: '~/.{{ item }}'
    state: link
  with_items:
    - zshrc
    - zprofile
    - tmux.conf
    - gitignore
    - gitconfig
    - emacs.d
