---
- file:
    src: '~/Dropbox/privatedotfiles/{{ item }}.sym'
    dest: '~/projects/dotfiles/{{ item }}.sym'
    state: link
  with_items:
    - zshenv.private
- file:
    src: '~/projects/dotfiles/{{ item }}.sym'
    dest: '~/.{{ item }}'
    state: link
  with_items:
    - zshenv
    - zshenv.private
    - zshrc
    - zprofile
    - tmux.conf
    - gitignore
    - gitconfig
    - emacs.d
    - default-gems
- user:
    name: "{{ ansible_facts['env']['USER'] }}"
    shell: /usr/local/bin/zsh
