---
- file:
    src: '~/Dropbox/privatedotfiles/{{ item }}.sym'
    dest: '~/projects/dotfiles/{{ item }}.sym'
    state: link
  with_items:
    - zshenv.private
- file:
    src: '~/projects/dotfiles/{{ item }}.sym'
    dest: '~/.{{ item }}'
    state: link
  with_items:
    - zshenv
    - zshenv.private
    - zshrc
    - zprofile
    - tmux.conf
    - gitignore
    - gitconfig
    - emacs.d
- name: Set shell
  command: dscl . -create /Users/$USER UserShell /usr/local/bin/zsh
  become: true
  become_user: root
