---
- homebrew:
  when: ansible_os_family == 'Darwin'
  name: "golang"

- shell: "GO111MODULE=off go get golang.org/x/tools/gopls@latest"
  args:
    creates: "{{ ansible_facts['env']['GOBIN'] }}/gopls"

- shell: "GO111MODULE=off go get github.com/go-delve/delve/cmd/dlv"
  args:
    creates: "{{ ansible_facts['env']['GOBIN'] }}/dlv"
