- homebrew: name=heroku/brew/heroku
  when: ansible_os_family == 'Darwin'
# heroku plugins:install api`
# heroku plugins:install heroku-event-log`
# heroku plugins:install heroku-pg-extras`
# heroku plugins:install heroku-sudo`
# heroku plugins:install heroku-cli-autocomplete
# heroku plugins:install heroku-enterprise
