---
- hosts: all
  roles:
    - asdf
  tasks:
    - include: tasks/keyboard.yml
    - include: tasks/dotfiles.yml
    - include: tasks/homebrew.yml
    - include: tasks/golang.yml
    - include: tasks/emacs.yml
    - include: tasks/heroku.yml
    - include: tasks/vpn.yml
    - include: tasks/packages.yml
  vars:
    - asdf_plugins:
      - name: ruby
        versions: ["2.6.3", "2.6.4"]
        global: "2.6.4"
      - name: golang
        versions: ["1.12", "1.13"]
        global: "1.13"
